/-
Copyright (c) 2026 Daniel Fagerström. All rights reserved.
Released under the Apache 2.0 license as described in the file LICENSES/Apache-2.0.txt.
Authors: Daniel Fagerström
-/
import SpatialLine
/-!
# The trust-boundary guard (release export)

`lake env lean CIAxiomGuard.lean` prints the axiom usage of every named declaration of this
export. Every axiom that appears must be one of Lean's three logical axioms or a name declared
in `blueprint/trust-boundary.txt` (the eleven interface names of the full development; the
paper's section 1.1 says which of them its theorems rest on). The list is the development
repository's guard restricted to the exported declarations; see README.md.
-/

#print axioms SpatialLine.CascadeFamily
#print axioms SpatialLine.IsScaleCovariant
#print axioms SpatialLine.IsPositiveDefinite
#print axioms SpatialLine.IsSymNegDef
#print axioms SpatialLine.IsSelfDecomposable
#print axioms SpatialLine.SymLevyPair.exponent
#print axioms SpatialLine.SDProfile.exponent
#print axioms SpatialLine.fourierCos
#print axioms SpatialLine.reflL1
#print axioms SpatialLine.cin
#print axioms SpatialLine.HasProfileTail
#print axioms SpatialLine.cinSuperpositionL
#print axioms SpatialLine.symbol
#print axioms SpatialLine.IsSubordinated
#print axioms SpatialLine.besselK
#print axioms SpatialLine.IsCompletelyMonotone
#print axioms SpatialLine.SignalClass
#print axioms SpatialLine.scaleGenerator
#print axioms SpatialLine.IsScaleLocallyGenerated
#print axioms SpatialLine.IsJointlyLocalOfOrder
#print axioms SpatialLine.signChangesAE
#print axioms SpatialLine.IsVariationDiminishing
#print axioms SpatialLine.IsPolyaExponent
#print axioms SpatialLine.integrable_cos_mul
#print axioms SpatialLine.integrable_sin_mul
#print axioms SpatialLine.fourierCos_dirac_zero
#print axioms SpatialLine.fourierCos_eq_charFun_re
#print axioms SpatialLine.charFun_eq_fourierCos_of_symmetric
#print axioms SpatialLine.fourier_uniqueness
#print axioms SpatialLine.levy_continuity
#print axioms SpatialLine.SymLevyPair.quadratic_growth
#print axioms SpatialLine.SymLevyPair.quadratic_growth_isBigO
#print axioms SpatialLine.SymLevyPair.exponentL_ne_top
#print axioms SpatialLine.profile_integrability
#print axioms SpatialLine.lintegral_ofReal_ne_top_of_integrableOn
#print axioms SpatialLine.sFinite_profileMeasure
#print axioms SpatialLine.profile_integrability_pair
#print axioms SpatialLine.profile_integrability_mem
#print axioms SpatialLine.laplace_uniqueness_locally_finite
#print axioms SpatialLine.charFun_eq_one_iff
#print axioms SpatialLine.lattice_zero_isClosedSubgroup
#print axioms SpatialLine.lattice_zero_trichotomy
#print axioms SpatialLine.lattice_zero_eq_univ_iff
#print axioms SpatialLine.lattice_zero_mem_iff
#print axioms SpatialLine.lattice_zero_exponent
#print axioms SpatialLine.lattice_zero_example_mem
#print axioms SpatialLine.lattice_zero_example_lattice
#print axioms SpatialLine.two_members_gaussian
#print axioms SpatialLine.gaussianCascadeFamily
#print axioms SpatialLine.eq_dirac_of_mconvL1_eq_id
#print axioms SpatialLine.norm_mconvL1_sub_le
#print axioms SpatialLine.tendsto_norm_mconvL1_sub_of_tendsto_charFun
#print axioms SpatialLine.integral_eq_zero_of_odd
#print axioms SpatialLine.integral_smul_exp_eq
#print axioms SpatialLine.ae_eq_zero_of_even_of_integral_cos_eq_zero
#print axioms SpatialLine.charFun_add_measure
#print axioms SpatialLine.integral_withDensity_ofReal
#print axioms SpatialLine.representation_existsUnique
#print axioms SpatialLine.representation_symmetric
#print axioms SpatialLine.representation_converse
#print axioms SpatialLine.nonvanishing
#print axioms SpatialLine.nonvanishing_exponent
#print axioms SpatialLine.dilation_invariance
#print axioms SpatialLine.dilation_atom
#print axioms SpatialLine.additivity
#print axioms SpatialLine.smoothed_transmittance
#print axioms SpatialLine.smoothed_transmittance_strictAnti
#print axioms SpatialLine.covariance_fourier
#print axioms SpatialLine.covariance_similarity
#print axioms SpatialLine.action_rigidity_injective
#print axioms SpatialLine.action_rigidity_group
#print axioms SpatialLine.action_rigidity_continuous
#print axioms SpatialLine.action_rigidity_no_fixed_point
#print axioms SpatialLine.monotonicity_zero_set
#print axioms SpatialLine.monotonicity_strict
#print axioms SpatialLine.no_lattice
#print axioms SpatialLine.canonical_gauge_orbit
#print axioms SpatialLine.canonical_gauge_of_levy
#print axioms SpatialLine.sub_one_sub_exp_neg_le
#print axioms SpatialLine.one_sub_sinc_ge
#print axioms SpatialLine.exists_limit_measure
#print axioms SpatialLine.increments_levy
#print axioms SpatialLine.canonical_gauge
#print axioms SpatialLine.increments_levy_infinitely_divisible
#print axioms SpatialLine.SDProfile.exponentL_ne_top
#print axioms SpatialLine.admissible_cone
#print axioms SpatialLine.sd_exponents_three_implies_one
#print axioms SpatialLine.sd_increment_pair
#print axioms SpatialLine.setLIntegral_Ioi_comp_mul
#print axioms SpatialLine.sd_dilate_pair
#print axioms SpatialLine.sd_increment_isSymLevyExponent
#print axioms SpatialLine.CascadeData.cascadeCore
#print axioms SpatialLine.CascadeData.continuousOn_mconvL1
#print axioms SpatialLine.ConstructionData.chi_continuousOn
#print axioms SpatialLine.exists_isSymmetric_of_isSymLevyExponent
#print axioms SpatialLine.main_construction
#print axioms SpatialLine.strict_positivity_monotone
#print axioms SpatialLine.gaussianDatum
#print axioms SpatialLine.gaussianDatum_exponent
#print axioms SpatialLine.semigroup_case_gaussian
#print axioms SpatialLine.lintegral_intervalIntegral_of_hasProfileTail
#print axioms SpatialLine.lintegral_min_one_sq_ne_top
#print axioms SpatialLine.lintegral_log_max_one_ne_top
#print axioms SpatialLine.measure_Ioi_ne_top
#print axioms SpatialLine.tendsto_measure_Ioi_nhdsGT
#print axioms SpatialLine.sd_exponents_profile_measure
#print axioms SpatialLine.hasDerivAt_cin
#print axioms SpatialLine.integrable_cin_dilate
#print axioms SpatialLine.exponent_eq_integral_cin
#print axioms SpatialLine.hasDerivAt_exponent
#print axioms SpatialLine.mul_deriv_exponent
#print axioms SpatialLine.symbolL_eq_ofReal
#print axioms SpatialLine.sd_exponents_symbol
#print axioms SpatialLine.sd_exponents_three_implies_two
#print axioms SpatialLine.symLevyPair_dilate
#print axioms SpatialLine.symLevyPair_add
#print axioms SpatialLine.dilate_le_of_increments
#print axioms SpatialLine.tonelli_window
#print axioms SpatialLine.setLIntegral_dyadicDensity
#print axioms SpatialLine.exists_antitone_density
#print axioms SpatialLine.SymLevyPair.measure_Ioi_ne_top
#print axioms SpatialLine.map_log_shift
#print axioms SpatialLine.map_exp_withDensity
#print axioms SpatialLine.dyadicDensity_ne_top
#print axioms SpatialLine.exists_profile_of_dilate_le
#print axioms SpatialLine.SDProfile.exponentL_neg
#print axioms SpatialLine.SDProfile.exponent_neg
#print axioms SpatialLine.sd_exponents_one_implies_three
#print axioms SpatialLine.SymLevyPair.continuous_exponent
#print axioms SpatialLine.SDProfile.continuous_exponent
#print axioms SpatialLine.main_uniqueness
#print axioms SpatialLine.fourierCos_eq_exp_neg_exponent
#print axioms SpatialLine.isSymLevyExponent_dilate_diff
#print axioms SpatialLine.exists_kernelFamily
#print axioms SpatialLine.main_analysis_of_profileForm
#print axioms SpatialLine.main_analysis
#print axioms SpatialLine.main_analysis_exists
#print axioms SpatialLine.main_characterization
#print axioms SpatialLine.ae_restrict_Ioi_mul_iff
#print axioms SpatialLine.SDProfile.k_eq_zero_of_dilation_ae
#print axioms SpatialLine.strict_positivity_strict
#print axioms SpatialLine.strict_positivity_consequences
#print axioms SpatialLine.isSelfDecomposable_kernel
#print axioms SpatialLine.kernel_ne_dirac_zero
#print axioms SpatialLine.kernel_regularity
#print axioms SpatialLine.integrableOn_stableIntegrand
#print axioms SpatialLine.stableConst_pos
#print axioms SpatialLine.stableDatum
#print axioms SpatialLine.stableDatum_exponent
#print axioms SpatialLine.semigroup_case_profile
#print axioms SpatialLine.eq_mul_of_addOn_of_continuousOn
#print axioms SpatialLine.exists_eq_rpow_of_mul
#print axioms SpatialLine.semigroup_case
#print axioms SpatialLine.cin_elementary
#print axioms SpatialLine.cin_expansion_zero
#print axioms SpatialLine.cin_expansion_top
#print axioms SpatialLine.cin_ray
#print axioms SpatialLine.cin_superposition
#print axioms SpatialLine.cin_superposition_exists
#print axioms SpatialLine.cin_origin_singularity_cin_ray
#print axioms SpatialLine.choquet_cone_forward
#print axioms SpatialLine.choquet_cone_surjective
#print axioms SpatialLine.choquet_cone_domain
#print axioms SpatialLine.choquet_cone_linear
#print axioms SpatialLine.choquet_cone_injective
#print axioms SpatialLine.choquet_cone_extreme_gaussian
#print axioms SpatialLine.choquet_cone_extreme_cin
#print axioms SpatialLine.choquet_cone_extreme_only
#print axioms SpatialLine.tail_eq_of_ae_tail_eq
#print axioms SpatialLine.measure_eq_of_tail_eq
#print axioms SpatialLine.cinSDProfile
#print axioms SpatialLine.choquetSDProfile
#print axioms SpatialLine.exists_tailMeasure
#print axioms SpatialLine.SDProfile.tendsto_k_atTop
#print axioms SpatialLine.sdProfile_unique
#print axioms SpatialLine.integrable_abs_of_exponent_le
#print axioms SpatialLine.cin_law_integrable_abs
#print axioms SpatialLine.integral_eq_integral_density
#print axioms SpatialLine.integrable_density
#print axioms SpatialLine.cin_delay_deriv_of_measure_form
#print axioms SpatialLine.measurable_windowMass
#print axioms SpatialLine.conv_delayWindow_eq_withDensity
#print axioms SpatialLine.charFun_delayWindow
#print axioms SpatialLine.hasDerivAt_fourierCos
#print axioms SpatialLine.integral_mul_sin_cin
#print axioms SpatialLine.integral_mul_cos_eq_zero_of_symmetric
#print axioms SpatialLine.charFun_jordan_sub
#print axioms SpatialLine.cin_delay_jordan
#print axioms SpatialLine.cin_delay_pairing
#print axioms SpatialLine.integral_delayWindow_deriv
#print axioms SpatialLine.cin_delay_measure_form
#print axioms SpatialLine.integrable_windowMassReal
#print axioms SpatialLine.cin_delay_pairing_density
#print axioms SpatialLine.cin_delay_equation
#print axioms SpatialLine.cin_delay_equation_deriv
#print axioms SpatialLine.integral_sin_mul_exp_neg_Ioi
#print axioms SpatialLine.integral_frullani
#print axioms SpatialLine.maternDatum
#print axioms SpatialLine.maternDatum_exponent
#print axioms SpatialLine.matern_exponent
#print axioms SpatialLine.matern_transforms
#print axioms SpatialLine.matern_gauge
#print axioms SpatialLine.matern_gauge_profile
#print axioms SpatialLine.matern_rational
#print axioms SpatialLine.matern_rational_polynomial
#print axioms SpatialLine.stable_family_bridge
#print axioms SpatialLine.eqOn_of_ae_eq_of_antitoneOn
#print axioms SpatialLine.eqOn_of_profileMeasure_eq
#print axioms SpatialLine.thorinExponent_dirac
#print axioms SpatialLine.eqOn_maternProfile_of_exponent
#print axioms SpatialLine.matern_thorin_atom
#print axioms SpatialLine.matern_kernels
#print axioms SpatialLine.matern_theorem
#print axioms SpatialLine.besselK_half
#print axioms SpatialLine.matern_density_special
#print axioms SpatialLine.student_density
#print axioms SpatialLine.matern_density_gaussian_limit
#print axioms SpatialLine.iteratedDeriv_scale_two
#print axioms SpatialLine.scale_evolution_conjugation
#print axioms SpatialLine.corner_generator_gaussian
#print axioms SpatialLine.corner_generator_cin
#print axioms SpatialLine.one_sub_inv_le_log
#print axioms SpatialLine.sigmaFinite_of_lintegral_ne_top
#print axioms SpatialLine.thorin_measure_facts
#print axioms SpatialLine.thorin_frullani
#print axioms SpatialLine.laplaceL_ne_top_of_facts
#print axioms SpatialLine.continuousOn_laplaceReal
#print axioms SpatialLine.lintegral_gaussian_one_sub_cos
#print axioms SpatialLine.lintegral_min_ne_top_of_profileJump_eq
#print axioms SpatialLine.laplaceL_eq_of_thorin
#print axioms SpatialLine.thorin_subclass_representation
#print axioms SpatialLine.sigmaFinite_of_laplaceL_ne_top
#print axioms ScaleSpace.CausalAdmissible.ofReal_mul_mixDensityL_laplace
#print axioms SpatialLine.isFolded_map_sqrt
#print axioms SpatialLine.integrable_expNegSq
#print axioms SpatialLine.continuous_erfc
#print axioms SpatialLine.erfc_pos
#print axioms SpatialLine.integral_Ioi_exp_neg_mul_const
#print axioms SpatialLine.erfc_le_two_mul_exp
#print axioms SpatialLine.hasDerivAt_inv_sq
#print axioms SpatialLine.antitoneOn_inv_sq
#print axioms SpatialLine.image_inv_sq
#print axioms SpatialLine.lintegral_Ioo_comp_inv_sq
#print axioms ScaleSpace.CausalAdmissible.bridgeProfile_of_cin
#print axioms SpatialLine.exists_laplaceL_lower_bound
#print axioms SpatialLine.thorin_bridge
#print axioms SpatialLine.lintegral_Ioi_exp_neg_mul
#print axioms SpatialLine.ofReal_one_sub_exp_div_eq_lintegral
#print axioms SpatialLine.lintegral_Ioc_inv_add
#print axioms SpatialLine.causal_thorin_frullani
#print axioms SpatialLine.min_one_le_exp_one_mul
#print axioms SpatialLine.measurable_halfSq
#print axioms SpatialLine.measurable_sqrtTwoMul
#print axioms SpatialLine.map_sqrtTwoMul_map_halfSq
#print axioms SpatialLine.map_halfSq_map_sqrtTwoMul
#print axioms SpatialLine.thorin_bridge_measure_linear
#print axioms SpatialLine.thorin_bridge_measure_injective
#print axioms SpatialLine.thorin_bridge_onto
#print axioms SpatialLine.thorin_strictness
#print axioms SpatialLine.laplaceL_gammaThorinMeasure
#print axioms SpatialLine.thorin_of_laplace
#print axioms SpatialLine.stable_family_thorin
#print axioms SpatialLine.lintegral_min_hasProfileTail
#print axioms SpatialLine.abs_secondDifference_le
#print axioms SpatialLine.scale_evolution_absconv
#print axioms SpatialLine.cin_pos
#print axioms SpatialLine.bridge_strictness_criterion
#print axioms SpatialLine.bridge_strictness_increasing
#print axioms SpatialLine.bridge_strictness_cin
#print axioms SpatialLine.bridge_strictness_stationary
#print axioms SpatialLine.bridge_strictness_cone
#print axioms SpatialLine.subordinated_members
#print axioms SpatialLine.measurable_brownianLaw
#print axioms SpatialLine.bridge_families_delay
#print axioms SpatialLine.bridge_families_stable
#print axioms ScaleSpace.CausalAdmissible.mixDensityL_ne_top
#print axioms ScaleSpace.CausalAdmissible.ofReal_mul_mixDensityL
#print axioms ScaleSpace.CausalAdmissible.bridgeProfile_antitoneOn
#print axioms ScaleSpace.CausalAdmissible.lintegral_min_profileMeasure_ne_top
#print axioms ScaleSpace.CausalAdmissible.profileJump_bridgeProfile
#print axioms ScaleSpace.CausalAdmissible.bridgeDatum_exponent
#print axioms SpatialLine.bridge_exponents
#print axioms SpatialLine.isProbabilityMeasure_bind_brownianLaw
#print axioms SpatialLine.isSymmetric_bind_brownianLaw
#print axioms SpatialLine.fourierCos_bind_brownianLaw
#print axioms SpatialLine.bridge_exponents_mixture
#print axioms ScaleSpace.CausalAdmissible.exponent_of_nonpos
#print axioms SpatialLine.bridgeConstruction_expo
#print axioms SpatialLine.bridgeConstruction_gaugeAction
#print axioms SpatialLine.bridgeDatum_ne_zero
#print axioms SpatialLine.bridge_families
#print axioms SpatialLine.integral_inverseGamma_brownian
#print axioms SpatialLine.lintegral_inverseGamma_brownian
#print axioms SpatialLine.bridge_families_bessel
#print axioms SpatialLine.lintegral_ofReal_ne_top_iff_integrableOn
#print axioms SpatialLine.stable_family_moments
#print axioms SpatialLine.matern_moments_integrable
#print axioms SpatialLine.mul_deriv_abs_rpow
#print axioms SpatialLine.corner_generator_stable_symbol
#print axioms SpatialLine.stableJump_tail
#print axioms SpatialLine.stable_jump_measure
#print axioms SpatialLine.corner_generator_stable
#print axioms SpatialLine.mconv_laplaceLaw
#print axioms SpatialLine.maternJump_tail
#print axioms SpatialLine.matern_jump_measure
#print axioms SpatialLine.integral_maternJump
#print axioms SpatialLine.corner_generator_matern
#print axioms SpatialLine.symbol_eq_mul_deriv
#print axioms SpatialLine.hasDerivAt_exponent_of_ne
#print axioms SpatialLine.scale_evolution_fourier
#print axioms SpatialLine.abs_mul_log_le
#print axioms SpatialLine.mul_log_le_sq
#print axioms SpatialLine.lintegral_exp_sq_eq_top
#print axioms SpatialLine.completely_monotone_support_unbounded
#print axioms SpatialLine.moments_tails_completely_monotone
#print axioms SpatialLine.lintegral_exp_mul_of_even
#print axioms SpatialLine.lintegral_Ioi_rpow_exp_besselKernel
#print axioms SpatialLine.lintegral_cosh_exp_eq_besselK
#print axioms SpatialLine.lintegral_Ioi_inverseGammaKernel
#print axioms SpatialLine.isProbabilityMeasure_inverseGammaLaw
#print axioms SpatialLine.lintegral_exp_neg_inverseGammaLaw
#print axioms SpatialLine.student_transform
#print axioms SpatialLine.lintegral_Ioi_comp_exp
#print axioms SpatialLine.lintegral_exp_neg_half_of_even
#print axioms SpatialLine.lintegral_besselK_half
#print axioms SpatialLine.lintegral_Ioi_firstPassage
#print axioms SpatialLine.integral_Ioi_firstPassage
#print axioms SpatialLine.bridgeProfile_of_exp
#print axioms SpatialLine.bridge_families_gamma
#print axioms SpatialLine.one_sub_cos_mul_two_div
#print axioms SpatialLine.exponent_eq_add_integral
#print axioms SpatialLine.tendsto_exponent_div
#print axioms SpatialLine.tendsto_one_sub_exp_div
#print axioms SpatialLine.lintegral_sq_le_of_tendsto
#print axioms SpatialLine.moments_tails_variance
#print axioms SpatialLine.maternTransform_zero
#print axioms SpatialLine.integral_id_mul_maternProfile
#print axioms SpatialLine.matern_mean_variance
#print axioms SpatialLine.two_members_matern_moments
#print axioms SpatialLine.lintegral_symmetrise_of_even
#print axioms SpatialLine.fourierCos_symmetrise
#print axioms SpatialLine.lintegral_pow_brownianLaw
#print axioms SpatialLine.lintegral_gammaMeasure_rpow_mul_exp
#print axioms SpatialLine.integral_exp_neg_maternDelay
#print axioms SpatialLine.fourierCos_maternDelay_bind
#print axioms SpatialLine.lintegral_pow_maternDelay_bind
#print axioms SpatialLine.matern_gamma_mixture
#print axioms SpatialLine.matern_moments
#print axioms SpatialLine.sub_translate_eq_intervalIntegral
#print axioms SpatialLine.lintegral_enorm_translate_sub_le
#print axioms SpatialLine.lintegral_enorm_secondDifference_le
#print axioms SpatialLine.lintegral_enorm_secondDifference_le_three
#print axioms SpatialLine.lintegral_enorm_secondDifference_le_min
#print axioms SpatialLine.sigmaFinite_of_hasProfileTail
#print axioms SpatialLine.symbol_eq_add
#print axioms SpatialLine.integral_kar_mul_secondDifference
#print axioms SpatialLine.integral_kar_mul_deriv
#print axioms SpatialLine.integral_kar_mul_iteratedDeriv_two
#print axioms SpatialLine.integrable_uncurry_kar_secondDifference
#print axioms SpatialLine.integral_kar_mul_scaleGenerator
#print axioms SpatialLine.scale_evolution_multiplier
#print axioms SpatialLine.expLaw_tail
#print axioms SpatialLine.integral_expLaw
#print axioms SpatialLine.isFolded_thorinJump
#print axioms SpatialLine.thorinJump_tail
#print axioms SpatialLine.thorin_jump_measure
#print axioms SpatialLine.integral_expLaw_secondDifference
#print axioms SpatialLine.integral_thorinJump
#print axioms SpatialLine.corner_generator_thorin
#print axioms SpatialLine.SignalClass.exists_bound_iteratedDeriv_two
#print axioms SpatialLine.integrable_prod_secondDifference
#print axioms SpatialLine.integral_secondDifference_mconv
#print axioms SpatialLine.integrable_mconv_secondDifference
#print axioms SpatialLine.scaleGenerator_mconv
#print axioms SpatialLine.conv_absolutelyContinuous
#print axioms SpatialLine.isSymmetric_conv
#print axioms SpatialLine.mconv_conv_bounded
#print axioms SpatialLine.signChangesAE_congr
#print axioms SpatialLine.measurable_mconv
#print axioms SpatialLine.mconv_bounded
#print axioms SpatialLine.exists_good_representative
#print axioms SpatialLine.isVariationDiminishing_conv
#print axioms SpatialLine.ae_eq_of_profileMeasure_eq_aemeasurable
#print axioms SpatialLine.abs_karPair_le
#print axioms SpatialLine.exists_bound_karPair
#print axioms SpatialLine.exists_bound_karPair_two
#print axioms SpatialLine.cosPair_eq
#print axioms SpatialLine.continuous_karPair
#print axioms SpatialLine.integral_sin_mul_eq_zero_of_symmetric
#print axioms SpatialLine.integral_cosPair_translate
#print axioms SpatialLine.re_exp_mul_fourier
#print axioms SpatialLine.im_fourier_ofReal
#print axioms SpatialLine.fourier_ofReal_eq
#print axioms SpatialLine.integrable_fourier_ofReal_of_bound
#print axioms SpatialLine.inversion_cosPair
#print axioms SpatialLine.mconv_eq_integral_cosPair
#print axioms SpatialLine.exists_bound_symbol
#print axioms SpatialLine.continuous_symbol
#print axioms SpatialLine.exists_bound_secondDifference
#print axioms SpatialLine.continuous_scaleGenerator_signal
#print axioms SpatialLine.integrable_scaleGenerator_signal
#print axioms SpatialLine.karPair_scaleGenerator
#print axioms SpatialLine.exists_bound_karPair_scaleGenerator
#print axioms SpatialLine.hasDerivAt_integral_transfer
#print axioms SpatialLine.scale_evolution_signal
#print axioms SpatialLine.IsVariationDiminishingOrd
#print axioms SpatialLine.signChanges_mono
#print axioms SpatialLine.signChangesAE_le_of_ae
#print axioms SpatialLine.signChangesAE_le
#print axioms SpatialLine.exists_measurable_rep_signChanges_le
#print axioms SpatialLine.signChangesAE_eq_iInf_measurable
#print axioms SpatialLine.isVariationDiminishing_of_ord
#print axioms SpatialLine.causalThorinDatum
#print axioms SpatialLine.causalThorinDatum_exponent
#print axioms SpatialLine.laplaceL_ne_top_of_causalThorin
#print axioms SpatialLine.student_subordinated
#print axioms SpatialLine.student_thorin
#print axioms SpatialLine.thorin_pair_mul
#print axioms SpatialLine.neg_log_norm_thorin_factor
#print axioms SpatialLine.thorin_pair_compensator
#print axioms SpatialLine.thorin_two_sided_fold
#print axioms SpatialLine.two_mul_ofReal_half
#print axioms SpatialLine.lintegral_Ioi_min_profile_ne_top
#print axioms SpatialLine.lintegral_foldedHalf_one_sub_cos
#print axioms SpatialLine.twoSided_k_add_neg
#print axioms SpatialLine.twoSided_exponent
#print axioms SpatialLine.twoSided_tendsto_nhdsGT
#print axioms SpatialLine.twoSided_tendsto_nhdsLT
#print axioms SpatialLine.folding_translation
#print axioms SpatialLine.TwoSidedProfile.integrableOn_satoIntegrand
#print axioms SpatialLine.integrableOn_foldedSatoIntegrand
#print axioms SpatialLine.twoSided_satoK
#print axioms SpatialLine.cin_origin_singularity_unbounded_of_sato
#print axioms SpatialLine.cin_origin_singularity_smooth_of_sato
#print axioms SpatialLine.cin_origin_singularity_threshold_of_sato
#print axioms SpatialLine.maternProfile_tendsto_nhdsGT
#print axioms SpatialLine.matern_origin_constant
#print axioms SpatialLine.SDProfile.k_le_of_tendsto_nhdsGT
#print axioms SpatialLine.one_le_satoK
#print axioms SpatialLine.measure_Ioo_le_of_density_le
#print axioms SpatialLine.le_measure_Ioo_of_le_density
#print axioms SpatialLine.not_le_of_le_density
#print axioms SpatialLine.integrableOn_thresholdIntegrand
#print axioms SpatialLine.thresholdExponent_antitone
#print axioms SpatialLine.integrableOn_thresholdComparison
#print axioms SpatialLine.log_le_thresholdComparison
#print axioms SpatialLine.cin_origin_singularity_unbounded
#print axioms SpatialLine.cin_origin_singularity_smooth
#print axioms SpatialLine.cin_origin_singularity_threshold
#print axioms SpatialLine.origin_boundedness
#print axioms SpatialLine.matern_origin_boundedness
